###########################
# known keywords for fixtures


group:      Grupo

round:      Rodada|Jornada

stage:  Fase de grupos|Fase final|Primeira Fase|Segunda Fase


### Knock out rounds

## fix: add playoffs + fifthplace

round32:        16-avos de final
round16:        Oitavos de final|Oitavas-de-final
quarterfinals:  Quartos de final|Quartas-de-final
semifinals:     Semifinais
thirdplace:     Terceiro lugar
final:          Final


### Pair matches/games if marked with leg1 n leg2

leg1:  1ยบ jogo    # Ida  -- exists ??
leg2:  2ยบ jogo    # Volta  -- exists ??
